CREATE TABLE `adatbazis`.`golyak` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT ,
    `nev` VARCHAR(256) NOT NULL ,
    `email` VARCHAR(256) NOT NULL ,
    `szak` VARCHAR(256) NOT NULL ,
    `telefonszam` VARCHAR(25) NOT NULL ,
    `cim` VARCHAR(256) NOT NULL ,
    `nem` BOOLEAN NOT NULL ,
    `oktatasiAzonosito` VARCHAR(20) NULL ,
    `szuletesiDatum` DATE NOT NULL ,
    `szuletesiHely` VARCHAR(128) NOT NULL ,
    `poloMeret` VARCHAR(6) NOT NULL ,
    `hetfo` BOOLEAN NOT NULL ,
    `kedd` BOOLEAN NOT NULL ,
    `szerda` BOOLEAN NOT NULL ,
    `csutortok` BOOLEAN NOT NULL ,
    `pentek` BOOLEAN NOT NULL ,
    `anyjaNeve` VARCHAR(256) NOT NULL ,
    `allergia` VARCHAR(512) NULL ,
    `etelerzekenyseg` VARCHAR(512) NULL ,
    `egyeb` VARCHAR(512) NULL ,
    `regisztracioDatuma` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    PRIMARY KEY (`id`),
    UNIQUE `unique_email` (`email`)) ENGINE = InnoDB;